# Generated by Django 2.2.6 on 2019-12-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(help_text='name of this service', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='description of this whitelist entry', max_length=255, null=True)),
                ('package_regex', models.CharField(blank=True, help_text='package regex', max_length=64, null=True)),
                ('enabled', models.BooleanField(default=False, help_text='enable patching on this pool')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('active', models.BooleanField(default=True, help_text='select if this record is currently active')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatchPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(help_text='name of this pool', max_length=32, unique=True)),
                ('description', models.CharField(blank=True, help_text='description of this patching pool', max_length=255, null=True)),
                ('hostname_regex', models.CharField(help_text='regex pattern for hosts in this pool', max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='enable patching on this pool')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatchPoolRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(help_text='name of this patching schedule', max_length=32, unique=True)),
                ('max_count_oos', models.IntegerField(default=0, help_text='max hosts (count) that can be out of service at a time')),
                ('max_percent_oos', models.FloatField(default=0, help_text='max hosts (percent) that can be out of service at a time')),
                ('min_count_is', models.IntegerField(default=0, help_text='min hosts (count) that must be in service at a time')),
                ('max_daily_percent', models.FloatField(default=0, help_text='max hosts (percent) that can be patched in a day')),
                ('enabled', models.BooleanField(default=False, help_text='enable patching on this pool')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatchQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('active', models.BooleanField(default=True, help_text='select if this record is currently active')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatchSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(help_text='name of this patching schedule', max_length=32, unique=True)),
                ('start_datetime', models.DateTimeField(help_text='start date and time for this patch schedule')),
                ('end_datetime', models.DateTimeField(help_text='start date and time for this patch schedule')),
                ('enabled', models.BooleanField(default=False, help_text='enable patching on this pool')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('enabled', models.BooleanField(default=False, help_text='enable patching on this service')),
                ('alerts_email', models.BooleanField(default=False, help_text='enable email alerts')),
                ('alerts_slack', models.BooleanField(default=False, help_text='enable slack alerts')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
