# Generated by Django 2.2.6 on 2019-12-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicemgr', '0001_initial'),
        ('hostmgr', '0002_host_service'),
        ('patchmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontrol',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicemgr.Service'),
        ),
        migrations.AddField(
            model_name='patchschedule',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchmgr.PatchPool'),
        ),
        migrations.AddField(
            model_name='patchpoolrule',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchmgr.PatchPool'),
        ),
        migrations.AddField(
            model_name='patchpool',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicemgr.Service'),
        ),
        migrations.AddField(
            model_name='patchevent',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmgr.Host'),
        ),
        migrations.AddField(
            model_name='patchevenstep',
            name='patch_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchmgr.PatchEvent'),
        ),
        migrations.AddField(
            model_name='packagewhitelist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicemgr.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='patchschedule',
            unique_together={('pool', 'name')},
        ),
    ]
