# Generated by Django 2.2.6 on 2019-12-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchmgr', '0002_auto_20191208_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecontrol',
            name='enabled',
        ),
        migrations.AddField(
            model_name='servicecontrol',
            name='patch_frequency',
            field=models.IntegerField(default=60, help_text='frequency, in days, of how often patch events should take place'),
        ),
        migrations.AddField(
            model_name='servicecontrol',
            name='patching_enabled',
            field=models.BooleanField(default=False, help_text='enable/disable patching on this service'),
        ),
        migrations.AddField(
            model_name='servicecontrol',
            name='script_path',
            field=models.CharField(default='/opt/patchmate/service_control_scripts', help_text='location on hosts where service control scripts live', max_length=64),
        ),
    ]
