# Generated by Django 2.2.6 on 2019-12-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemgr', '0001_initial'),
        ('patchmgr', '0002_auto_20191210_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagewhitelist',
            options={},
        ),
        migrations.AlterField(
            model_name='packagewhitelist',
            name='name',
            field=models.CharField(help_text='name of this service', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='packagewhitelist',
            unique_together={('service', 'name')},
        ),
    ]
