# Generated by Django 2.2.6 on 2019-12-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0002_host_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='in_service',
            field=models.BooleanField(default=False, help_text='flag to determine if this host is in service'),
        ),
    ]
