# Generated by Django 2.2.6 on 2019-12-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicemgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='patch_frequency',
        ),
        migrations.RemoveField(
            model_name='service',
            name='patching_enabled',
        ),
        migrations.RemoveField(
            model_name='service',
            name='script_path',
        ),
    ]
